# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
install: pip install -r hermodserver/requirements.txt
before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/hermodserver.py"
  - export FLASK_DEBUG=1
script: flask test
