# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
install: pip install -r hermodserver/requirements.txt
addons:
  sonarcloud:
    organization: "walterjgsp-github" # the key of the org you chose at step #3
    token: $SONAR_TOKEN
before_script:
  - cd hermodserver
  - export FLASK_APP="hermodserver.py"
  - export FLASK_DEBUG=1
script:
  - flask test
  - sonar-scanner
